# Generated by Django 4.1 on 2022-11-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='graduation_year',
            field=models.CharField(choices=[('2020/2021', '2020/2021'), ('2021/2022', '2021/2022'), ('2022/2023', '2022/2023'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026'), ('2026/2027', '2026/2027')], default='UNKOWN', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='study_year',
            field=models.CharField(choices=[('ADM', 'Admin'), ('STU', 'Student')], default='STU', max_length=10, null=True),
        ),
    ]
