# Generated by Django 4.1 on 2022-11-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_graduation_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='study_year',
            field=models.CharField(choices=[('ADM', 'Admin'), ('REC', 'Recruiter'), ('STU', 'Student')], default='STU', max_length=10, null=True),
        ),
    ]
