# Generated by Django 4.1 on 2022-11-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_about_alter_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('ADM', 'Admin'), ('REC', 'Recruiter'), ('STU', 'Student')], default='STU', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='study_year',
            field=models.CharField(choices=[('1st', '1st Year'), ('2nd', '2nd Year'), ('3rd', '3rd Year'), ('4th', '4th Year')], default='UNKOWN', max_length=10, null=True),
        ),
    ]
