# Generated by Django 4.1 on 2022-11-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_skill'),
        ('users', '0006_alter_customuser_about_alter_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.ManyToManyField(to='core.skill'),
        ),
    ]
