# Generated by Django 4.1 on 2022-11-18 19:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_joblisting_applicants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='applicants', to=settings.AUTH_USER_MODEL),
        ),
    ]
